{{- range .Values.ingress.tls}}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .secretName }}
spec:
  secretName: {{ .secretName }}
  renewBefore: 240h
  dnsNames:
    {{- range .hosts }}
  - '{{ . }}'
    {{- end }}
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
{{- end }}
